language: android
env:
  matrix:
  - ANDROID_API=android-10 ANDROID_ABI=armeabi-v7a
  - ANDROID_API=android-15 ANDROID_ABI=armeabi-v7a
  - ANDROID_API=android-16 ANDROID_ABI=armeabi-v7a
  - ANDROID_API=android-17 ANDROID_ABI=armeabi-v7a
  - ANDROID_API=android-18 ANDROID_ABI=armeabi-v7a
  - ANDROID_API=android-19 ANDROID_ABI=armeabi-v7a
  - ANDROID_API=android-21 ANDROID_ABI=armeabi-v7a
  global:
    - secure: "A6Wxi4weq44d3Ppc7H+sGpGBMZ4B1UTbu+Phn769tjRclEPVf0bUin13jAnKfcEk3owbHRVffOSmpqvhDu7hSkG5XutIiVGoiD5W39Iw6eeIn5S8jZ/oYEo5T9JQ2dMcKmYUGPOTznrezxwpbGkj6YBcdquSACSeqNoB8J6fR9A="
    - secure: "aTMPEs8BADkSwSYYI209LlZelWdEOWGfomaKienoOUAWTM2MvX1F6KFPwj/C39S6X5+XzZW/U3JzuN2uvBfd6pdWkH/yA8bTHj0nn8/N9CHRKMuvjEDOGKPjfBiCAWgJt+m2GWyT3hNA+XA0A10WgIB22JIrehIZHMCzE7wIJlc="
    - secure: "mXfFhvD6bqZGFMUt+QuDYCSMcy4Eol2dWyfUbiPjQ36boVU08qpnpUpAOo5++U2eHl2PRJpyRrspyJ8OgXoBkCB15yvegEQGi6O8xYkRqQa/Ax1ClDaXoWtYtbdz5lORIqJ9gNS4oevMOb0EBfGqGh4IUWj2g7akX65VHPo/Ies="
    - secure: "0GM+2wBdoZJA84N0BICH6Y0ReE+STFx1D109VK70yN0bdJ5rau2FXWK6jseeFIciXRraTNyl4V5Y84yOzKK3YXxLesk8mwcFFksE6bZlkPcJ55wrEwjbWR9gsi3t6GWzZ24URD0B2SMKyPbSxPX8SD/U4t2UWsjB2TGTglRRuV8="
matrix:
  allow_failures:
  - env: ANDROID_API=android-21 ANDROID_ABI=x86_64
  - env: ANDROID_API=android-24 ANDROID_ABI=x86_64
os:
- linux
dist: trusty
sudo: required
before_install:
- travis_wait 60 ./dependencies.sh
before_script:
- . ./setenv.sh
script:
- travis_wait 60 ./travis.sh
after_failure:
- cat emulator.log
- cat logcat.log
after_success:
- echo ${TEST_VAR}
- gradle uploadArchives
- mvn deploy --settings settings.xml
